spring:
  application:
    name: recycing
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.100.41/ares
    username: root
    password: 123456


server:
  port: 7001



logging:
  level:
    com:
      ares:
        recyce:
          mapper: debug
--- # eureka
eureka:
  instance:
    homePageUrl: http://47.99.100.41:8080
    preferIpAddress: false


--- # apollo 相关配置
app:
  id: Ares
apollo:
  meta: http://localhost:8080
  bootstrap:
    enabled: true
    namespaces: application
    eagerLoad:
      enabled: true